version: 0.3

phases:
  install:
     runtime-versions:
       java: corretto8
    comamands:
        - echo Executing Install Phase
        - echo Executing Second part ofInstall Phase 
    finally:
        - echo Executing Install Finally
  pre_build:
    commands:
         - echo Executing Pre Build Phase
    finally:
         - echo Executing Pre Build Phase
  build:
    commands:
         - echo Build started on `date`
    finally:
         - echo Executing build Finally 
  post_build:
    commands:
        - echo Executing Post Build Phase
    finally:
        - echo Executing Posy Build Finally
